apiVersion: v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image:
        ports:
        - containerPort: 5000